"""Generate the GitHub Actions cron schedule anchored to real match-end times.

GitHub's scheduler throttles/drops high-frequency crons (``*/15``), so instead of
polling blindly we schedule discrete checks a few minutes after every fixture is
expected to finish. Each scheduled run is still the *cheap* change-gate (collect
+ fingerprint); it only triggers the heavy 50k-sim + deploy when a new result is
detected. Follow-up offsets absorb stoppage time, knockout extra-time/penalties,
ESPN's posting lag, and GitHub's own scheduler delay.

It rewrites the block between the SCHEDULE:START/END markers in
``.github/workflows/update.yml`` (kept under version control so the schedule is
reproducible). Re-run whenever the fixture list changes:

    python3 scripts/gen_schedule.py            # fetch fixtures from ESPN, patch workflow
    python3 scripts/gen_schedule.py --print     # just print the cron block

Kickoffs repeat at the same UTC slots most days, so we emit one cron per distinct
HH:MM over months 6,7 (day = *). Non-match days simply run the cheap gate and
short-circuit, which is essentially free on a public repo.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from wc2026_bet import espn

REPO = Path(__file__).resolve().parents[2]
WORKFLOW = REPO / ".github" / "workflows" / "update.yml"
START = "# SCHEDULE:START (generated by scripts/gen_schedule.py - do not edit by hand)"
END = "# SCHEDULE:END"

# minutes after kickoff to run the cheap check:
#   120 = ~match end (90 + 15 HT + stoppage) + 5 min buffer
#   150 = +30 safety net (late ESPN posting / GitHub scheduler delay)
#   180 = +60 catch-all (knockout extra-time + penalties, very late posting)
OFFSETS = (120, 150, 180)

# a daily forced full run (no matches near this UTC time) so betting-odds drift is
# refreshed even on days without a finished match. The detect step force-matches it.
FORCED_CRON = "0 12 * 6,7 *"


def check_times() -> list[tuple[int, int]]:
    """Distinct (hour, minute) UTC marks = every kickoff + each OFFSET."""
    kicks: set[tuple[int, int]] = set()
    for f in espn.fetch_fixtures():
        d = f.get("date")
        if not d:
            continue
        t = dt.datetime.fromisoformat(d.replace("Z", "+00:00")).astimezone(dt.timezone.utc)
        kicks.add((t.hour, t.minute))
    out: set[tuple[int, int]] = set()
    for h, m in kicks:
        base = h * 60 + m
        for off in OFFSETS:
            tm = (base + off) % (24 * 60)
            out.add((tm // 60, tm % 60))
    return sorted(out)


def build_block(times: list[tuple[int, int]]) -> str:
    lines = [f"    {START}",
             f'    - cron: "{FORCED_CRON}"   # daily forced odds refresh (dead zone, no matches)']
    for h, m in times:
        lines.append(f'    - cron: "{m} {h} * 6,7 *"')
    lines.append(f"    {END}")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", action="store_true", help="print the block, do not patch")
    args = ap.parse_args()

    times = check_times()
    block = build_block(times)
    print(f"# {len(times)} match-end check times (offsets {OFFSETS} min) + 1 forced daily run")
    if args.print:
        print(block)
        return

    text = WORKFLOW.read_text(encoding="utf-8")
    pat = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        raise SystemExit(f"markers not found in {WORKFLOW}; add SCHEDULE:START/END first")
    # re.sub treats backslashes specially - pass the replacement as a function
    text = pat.sub(lambda _m: block.strip(), text, count=1)
    WORKFLOW.write_text(text, encoding="utf-8")
    print(f"Patched {WORKFLOW} with {len(times) + 1} cron lines.")


if __name__ == "__main__":
    main()
